import type { Metadata } from 'next'

import { LogoLink } from '@/components/Auth/LogoLink'
import { RegisterForm } from '@/components/Auth/register/RegisterForm'

export const metadata: Metadata = {
  title: 'Register',
  description: 'Generated by create next app',
}

export default function RegisterPage() {
  return (
    <div className="h-full w-full">
      <div className="flex min-h-screen items-center justify-center">
        <div className="my-20">
          <div className="flex flex-col items-center">
            <LogoLink />
            <RegisterForm />
          </div>
        </div>
      </div>
    </div>
  )
}
