import type { Metadata } from 'next'
import Hero from '@/components/Hero/Hero'
import { CategoryProductsSlider } from '@/components/CategoryProductsSlider/CategoryProductsSlider'
import { SubHero } from '@/components/SubHero/SubHero'
import { About } from '@/components/About/About'
import { Benefits } from '@/components/Benefits/Benefits'
import { Callback } from '@/components/Callback/Callback'
import { PaymentDelivery } from '@/components/PaymentDelivery/PaymentDelivery'
import { ContactsMap } from '@/components/ContactsMap/ContactsMap'
import PageWrapper from './PageWrapper'
import { FavoriteTabs } from '@/components/FavoriteTabs/FavoriteTabs'

export const metadata: Metadata = {
  title: 'Главная',
  description: 'Generated by create next app',
}

export default function Home() {
  return (
    <PageWrapper>
      <Hero />
      <CategoryProductsSlider />
      <SubHero />
      <FavoriteTabs />
      <About />
      <Benefits />
      <Callback />
      <PaymentDelivery level={'h2'} />
      <ContactsMap />
    </PageWrapper>
  )
}
