import type { Metadata } from 'next'
import Hero from '@/components/Hero/Hero'
import { CategoryProductsSlider } from '@/components/CategoryProductsSlider/CategoryProductsSlider'
import { SubHero } from '@/components/SubHero/SubHero'
import { About } from '@/components/About/About'
import { Benefits } from '@/components/Benefits/Benefits'
import { Callback } from '@/components/Callback/Callback'
import { PaymentDelivery } from '@/components/PaymentDelivery/PaymentDelivery'
import { ContactsMap } from '@/components/ContactsMap/ContactsMap'
import PageWrapper from './PageWrapper'
import { FavoriteTabs } from '@/components/FavoriteTabs/FavoriteTabs'
import { getPopularProducts } from '@/utils/api/products'
import { cardDataProps } from '@/types/products.types'

export const metadata: Metadata = {
  title: 'Главная',
  description: 'Generated by create next app',
}

interface FavoriteList {
  tires: cardDataProps[]
  battery: cardDataProps[]
  oils: cardDataProps[]
}

export default async function Home() {
  const response = await getPopularProducts()

  const formattedProducts: FavoriteList = {
    tires: response.data.filter(
      (product: cardDataProps) => product.categoryName === 'tires',
    ),
    battery: response.data.filter(
      (product: cardDataProps) => product.categoryName === 'battery',
    ),
    oils: response.data.filter(
      (product: cardDataProps) => product.categoryName === 'oils',
    ),
  }
  return (
    <PageWrapper>
      <Hero />
      <CategoryProductsSlider />
      <SubHero />
      <FavoriteTabs initialData={formattedProducts} />
      <About />
      <Benefits />
      <Callback />
      <PaymentDelivery level={'h2'} />
      <ContactsMap />
    </PageWrapper>
  )
}
