import { AuthBottomNav } from '@/components/Auth/AuthBottomNav'
import { LogoLink } from '@/components/Auth/LogoLink'
import { SocialAuthButtons } from '@/components/Auth/SocialAuthButtons'
import { SubmitBtn } from '@/components/Auth/SubmitBtn'
import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'Login',
  description: 'Generated by create next app',
}

export default function LoginPage() {
  return (
    <div className="h-full w-full">
      <div className="flex min-h-screen items-center justify-center">
        <div className="my-20">
          <div className="flex flex-col items-center">
            <LogoLink />
            <div className="flex max-w-96 flex-col">
              <div className="flex w-full min-w-96 max-w-96 flex-col overflow-hidden rounded-lg bg-white p-10 shadow-custom">
                <div className="flex flex-col">
                  <form className="grid grid-cols-1 gap-4">
                    <div className="text-center">
                      <h1 className="text-2xl font-bold leading-5 text-darkBlue">
                        Войти
                      </h1>
                    </div>
                    <div className="flex flex-col gap-4">
                      <div className="flex flex-col">
                        <div className="input_css_inputRoot_iit11wh">
                          <label
                            htmlFor="baseInput___LLt-2"
                            className="mb-1 text-sm font-medium leading-5 text-[#5d5d5f]"
                          >
                            Адрес электронной почты
                          </label>
                          <div className="flex min-h-10 w-full items-center gap-2 rounded-lg border bg-[#fcfcfc] px-2.5 shadow-sm outline-none">
                            <div className="relative flex-1">
                              <div className="flex w-full overflow-x-auto whitespace-nowrap">
                                <div className="flex flex-1 items-center gap-1">
                                  {/* <div className=""></div> */}
                                  <input
                                    className="w-full py-2.5 focus:shadow-none focus:outline-none"
                                    type="email"
                                    name="Email"
                                    placeholder="e-mail@yandex.ru"
                                    autoFocus={true}
                                  />
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div className="mocked-styled-0 stack_css_StackRoot_s1yn6md3">
                        <div className="input_css_inputRoot_iit11wh">
                          <label
                            htmlFor="baseInput___ivZ35"
                            className="mb-1 text-sm font-medium leading-5 text-[#5d5d5f]"
                          >
                            Пароль
                          </label>
                          <div className="flex min-h-10 w-full items-center gap-2 rounded-lg border bg-[#fcfcfc] px-2.5 shadow-sm outline-none hover:border-black">
                            <div className="relative flex-1">
                              <div className="flex w-full overflow-x-auto whitespace-nowrap">
                                <div className="flex flex-1 items-center gap-1">
                                  {/* <div className="input_css_beforeInputWrapper_bqn0sj7"></div> */}
                                  <input
                                    className="w-full py-2.5 focus:outline-none"
                                    name="password"
                                    placeholder="Пароль"
                                    type="password"
                                    id="baseInput___ivZ35"
                                  />
                                </div>
                              </div>
                            </div>
                            <div className="cursor-pointer">
                              <svg
                                xmlns="http://www.w3.org/2000/svg"
                                width="20"
                                height="20"
                                fill="none"
                                viewBox="0 0 24 24"
                                className="h-5 w-5"
                              >
                                <path
                                  stroke="currentColor"
                                  strokeLinecap="round"
                                  strokeLinejoin="round"
                                  strokeWidth="1.4"
                                  d="M2.268 12.7c-.138-.211-.207-.317-.246-.48a1.115 1.115 0 0 1 0-.44c.039-.163.108-.269.246-.48C3.411 9.55 6.814 5.125 12 5.125c5.186 0 8.589 4.424 9.732 6.175.138.211.208.317.246.48.03.123.03.317 0 .44-.038.163-.108.269-.246.48-1.143 1.75-4.546 6.175-9.732 6.175-5.186 0-8.589-4.424-9.732-6.175Z"
                                ></path>
                                <path
                                  stroke="currentColor"
                                  strokeLinecap="round"
                                  strokeLinejoin="round"
                                  strokeWidth="1.4"
                                  d="M12 14.947c1.683 0 3.048-1.32 3.048-2.947S13.683 9.054 12 9.054 8.953 10.373 8.953 12c0 1.627 1.364 2.947 3.047 2.947Z"
                                ></path>
                              </svg>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    <div
                      className="mocked-styled-0 stack_css_StackRoot_s1yn6md3"
                      data-stack="1"
                    >
                      <SubmitBtn text={'Вход'} />
                    </div>
                  </form>
                  <SocialAuthButtons />
                </div>
              </div>
              <AuthBottomNav login />
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
