import { Callback } from '@/components/Callback/Callback'
import { CatalogMain } from '@/components/CatalogMain/CatalogMain'
import BreadCrumbs from '@/components/ui/BreadCrumbs/BreadCrumbs'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Каталог',
  description: 'Generated by create next app',
}

export default function CatalogPage() {
  return (
    <>
      <BreadCrumbs />
      <CatalogMain />
      <Callback />
    </>
  )
}
