import { Callback } from '@/components/Callback/Callback'
import { Favorite } from '@/components/Favorite/Favorite'
import type { Metadata } from 'next'
import PageWrapper from '../PageWrapper'

export const metadata: Metadata = {
  title: 'Избранное',
  description: 'Generated by create next app',
}

export default function FavoritePage() {
  return (
    <PageWrapper>
      <Favorite />
      <Callback />
    </PageWrapper>
  )
}
