import { Callback } from '@/components/Callback/Callback'
import { Cart } from '@/components/Cart/Cart'
import type { Metadata } from 'next'
import PageWrapper from '../PageWrapper'

export const metadata: Metadata = {
  title: 'Корзина',
  description: 'Generated by create next app',
}

export default function CartPage() {
  return (
    <PageWrapper>
      <Cart />
      <Callback />
    </PageWrapper>
  )
}
