import { Callback } from '@/components/Callback/Callback'
import { Cart } from '@/components/Cart/Cart'
import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Корзина',
  description: 'Generated by create next app',
}

export default function CartPage() {
  return (
    <>
      <Cart />
      <Callback />
    </>
  )
}
