import { Callback } from '@/components/Callback/Callback'
import { Cart } from '@/components/Cart/Cart'
import type { Metadata } from 'next'
import PageWrapper from '../PageWrapper'
import TransitionWrapper from '@/providers/TransitionWrapper'

export const metadata: Metadata = {
  title: 'Корзина',
  description: 'Generated by create next app',
}

export default function CartPage() {
  return (
    <TransitionWrapper>
      <PageWrapper>
        <Cart />
        <Callback />
      </PageWrapper>
    </TransitionWrapper>
  )
}
