import type { Metadata } from 'next'
import { Callback } from '@/components/Callback/Callback'
import { PaymentDelivery } from '@/components/PaymentDelivery/PaymentDelivery'
import { ContactsMap } from '@/components/ContactsMap/ContactsMap'
import BreadCrumbs from '@/components/ui/BreadCrumbs/BreadCrumbs'
import { Requisites } from '@/components/Requisites/Requisites'

export const metadata: Metadata = {
  title: 'Контакты',
  description: 'Generated by create next app',
}

export default function RequisitesPage() {
  return (
    <>
      <BreadCrumbs />
      <Requisites />
      <Callback />
      <ContactsMap />
    </>
  )
}
