import type { Metadata } from 'next'
import { Callback } from '@/components/Callback/Callback'
import { PaymentDelivery } from '@/components/PaymentDelivery/PaymentDelivery'
import { ContactsMap } from '@/components/ContactsMap/ContactsMap'
import BreadCrumbs from '@/components/ui/BreadCrumbs/BreadCrumbs'
import PageWrapper from '../PageWrapper'

export const metadata: Metadata = {
  title: 'Контакты',
  description: 'Generated by create next app',
}

export default function PaymentDeliveryPage() {
  return (
    <PageWrapper>
      <BreadCrumbs />
      <PaymentDelivery level={'h1'} />
      <Callback />
      <ContactsMap />
    </PageWrapper>
  )
}
